package com.jfnice.model;

import com.jfnice.model.base.BaseAsset;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Asset extends BaseAsset<Asset> {
	public static final Asset dao = new Asset().dao();
}
