package com.jfnice.model;

import com.jfnice.model.base.BaseBookStorageItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookStorageItem extends BaseBookStorageItem<BookStorageItem> {
	public static final BookStorageItem dao = new BookStorageItem().dao();
}
