package com.jfnice.model;

import com.jfnice.model.base.BaseBookStorage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookStorage extends BaseBookStorage<BookStorage> {
	public static final BookStorage dao = new BookStorage().dao();
}
