package com.jfnice.model;

import com.jfnice.model.base.BaseBookInventoryItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookInventoryItem extends BaseBookInventoryItem<BookInventoryItem> {
	public static final BookInventoryItem dao = new BookInventoryItem().dao();
}
