package com.jfnice.model;

import com.jfnice.model.base.BaseBookStorageItemBarCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookStorageItemBarCode extends BaseBookStorageItemBarCode<BookStorageItemBarCode> {
	public static final BookStorageItemBarCode dao = new BookStorageItemBarCode().dao();
}
