package com.jfnice.model;

import com.jfnice.model.base.BaseBookDamaged;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookDamaged extends BaseBookDamaged<BookDamaged> {
	public static final BookDamaged dao = new BookDamaged().dao();
}
