package com.jfnice.model;

import com.jfnice.model.base.BaseBookInventory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookInventory extends BaseBookInventory<BookInventory> {
	public static final BookInventory dao = new BookInventory().dao();
}
