package com.jfnice.model;

import com.jfnice.model.base.BaseBookBarCode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookBarCode extends BaseBookBarCode<BookBarCode> {
	public static final BookBarCode dao = new BookBarCode().dao();
}
