package com.jfnice.model;

import com.jfnice.model.base.BaseBorrowBookHis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BorrowBookHis extends BaseBorrowBookHis<BorrowBookHis> {
	public static final BorrowBookHis dao = new BorrowBookHis().dao();
}
