package com.jfnice.model;

import com.jfnice.model.base.BaseBorrowSetting;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BorrowSetting extends BaseBorrowSetting<BorrowSetting> {
	public static final BorrowSetting dao = new BorrowSetting().dao();
}
