package com.jfnice.model;

import com.jfnice.model.base.BaseBorrowBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BorrowBook extends BaseBorrowBook<BorrowBook> {
	public static final BorrowBook dao = new BorrowBook().dao();
}
