package com.jfnice.model;

import com.jfnice.model.base.BaseCatalog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Catalog extends BaseCatalog<Catalog> {
	public static final Catalog dao = new Catalog().dao();
}
