package com.jfnice.model;

import com.jfnice.model.base.BaseDepositRechargeHis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepositRechargeHis extends BaseDepositRechargeHis<DepositRechargeHis> {
	public static final DepositRechargeHis dao = new DepositRechargeHis().dao();
}
