package com.jfnice.model;

import com.jfnice.model.base.BaseDepositRecharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepositRecharge extends BaseDepositRecharge<DepositRecharge> {
	public static final DepositRecharge dao = new DepositRecharge().dao();
}
