package com.jfnice.model;

import com.jfnice.model.base.BaseDepositReturnHis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepositReturnHis extends BaseDepositReturnHis<DepositReturnHis> {
	public static final DepositReturnHis dao = new DepositReturnHis().dao();
}
