package com.jfnice.model;

import com.jfnice.model.base.BaseDepositReturn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepositReturn extends BaseDepositReturn<DepositReturn> {
	public static final DepositReturn dao = new DepositReturn().dao();
}
