package com.jfnice.model;

import com.jfnice.model.base.BaseSearch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Search extends BaseSearch<Search> {
	public static final Search dao = new Search().dao();
}
