package com.jfnice.model;

import com.jfnice.model.base.BaseUserInfoHis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserInfoHis extends BaseUserInfoHis<UserInfoHis> {
	public static final UserInfoHis dao = new UserInfoHis().dao();
}
