/**
 * Generated by JFnice (www.jfnice.com).
 */

package com.jfnice._gen.#(lowercaseModelName);

import java.util.List;
import java.util.Map;

import com.jfnice.core.JFniceBaseService;
import com.jfnice.ext.ErrorMsg;
import com.jfnice.model.#(modelName);

public class #(modelName)Service extends JFniceBaseService<#(modelName)> {
	
	public static final #(modelName)Service me = new #(modelName)Service();
	
	public List<#(modelName)> getTreeList(String fields) {
		return getTreeList(fields, false);
	}
	
	public List<#(modelName)> getTreeList(String fields, boolean showAllStatusFlag) {
		#(modelName) #(firstCharLowerModelName) = new #(modelName)().set("id", 0L);
		addAttrChildList(#(firstCharLowerModelName), fields, true);
		return #(firstCharLowerModelName).get("children");
	}
	
	public boolean save(#(modelName) #(firstCharLowerModelName)) {
		if ( !isUnique(#(firstCharLowerModelName), "name") ) {
			throw new ErrorMsg("名称已存在！");
		}
		
		boolean flag = super.save(#(firstCharLowerModelName));
		#(modelName)IdMap.me.clear();
		return flag;
	}

	public boolean update(#(modelName) #(firstCharLowerModelName)) {
		if ( !isUnique(#(firstCharLowerModelName), "name") ) {
			throw new ErrorMsg("名称已存在！");
		}
		
		boolean flag = super.update(#(firstCharLowerModelName));
		#(modelName)IdMap.me.clear();
		return flag;
	}
	
	public boolean deleteById(long #(firstCharLowerModelName)Id, boolean isRealDelete) {
		#(modelName) #(firstCharLowerModelName) = queryById(#(firstCharLowerModelName)Id);
		if ( hasChild(#(firstCharLowerModelName)) ) {
			throw new ErrorMsg("请先删除子节点！");
		}
		
		boolean flag = super.deleteById(#(firstCharLowerModelName)Id, isRealDelete);
		#(modelName)IdMap.me.clear();
		return flag;
	}
	
	public <K, V> int[] sort(Map<K, V> map) {
		int[] arr = super.sort(map);
		#(modelName)IdMap.me.clear();
		return arr;
	}
	
}