package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBorrowBookHis<M extends BaseBorrowBookHis<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setDel(java.lang.Boolean del) {
		set("del", del);
	}
	
	public java.lang.Boolean getDel() {
		return get("del");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserCode(java.lang.String createUserCode) {
		set("create_user_code", createUserCode);
	}
	
	public java.lang.String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public void setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
	}
	
	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserCode(java.lang.String updateUserCode) {
		set("update_user_code", updateUserCode);
	}
	
	public java.lang.String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public void setSchoolCode(java.lang.String schoolCode) {
		set("school_code", schoolCode);
	}
	
	public java.lang.String getSchoolCode() {
		return getStr("school_code");
	}

	public void setGrdCode(java.lang.String grdCode) {
		set("grd_code", grdCode);
	}
	
	public java.lang.String getGrdCode() {
		return getStr("grd_code");
	}

	public void setGrdName(java.lang.String grdName) {
		set("grd_name", grdName);
	}
	
	public java.lang.String getGrdName() {
		return getStr("grd_name");
	}

	public void setClsCode(java.lang.String clsCode) {
		set("cls_code", clsCode);
	}
	
	public java.lang.String getClsCode() {
		return getStr("cls_code");
	}

	public void setClsName(java.lang.String clsName) {
		set("cls_name", clsName);
	}
	
	public java.lang.String getClsName() {
		return getStr("cls_name");
	}

	public void setStuCode(java.lang.String stuCode) {
		set("stu_code", stuCode);
	}
	
	public java.lang.String getStuCode() {
		return getStr("stu_code");
	}

	public void setSno(java.lang.String sno) {
		set("sno", sno);
	}
	
	public java.lang.String getSno() {
		return getStr("sno");
	}

	public void setDptName(java.lang.String dptName) {
		set("dpt_name", dptName);
	}
	
	public java.lang.String getDptName() {
		return getStr("dpt_name");
	}

	public void setBorrower(java.lang.String borrower) {
		set("borrower", borrower);
	}
	
	public java.lang.String getBorrower() {
		return getStr("borrower");
	}

	public void setCatalogName(java.lang.String catalogName) {
		set("catalog_name", catalogName);
	}
	
	public java.lang.String getCatalogName() {
		return getStr("catalog_name");
	}

	public void setCheckNo(java.lang.String checkNo) {
		set("check_no", checkNo);
	}
	
	public java.lang.String getCheckNo() {
		return getStr("check_no");
	}

	public void setPrice(java.lang.Integer price) {
		set("price", price);
	}
	
	public java.lang.Integer getPrice() {
		return getInt("price");
	}

	public void setBookName(java.lang.String bookName) {
		set("book_name", bookName);
	}
	
	public java.lang.String getBookName() {
		return getStr("book_name");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public void setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
	}
	
	public java.lang.String getPublisher() {
		return getStr("publisher");
	}

	public void setPublishDate(java.util.Date publishDate) {
		set("publish_date", publishDate);
	}
	
	public java.util.Date getPublishDate() {
		return get("publish_date");
	}

	public void setBarCode(java.lang.String barCode) {
		set("bar_code", barCode);
	}
	
	public java.lang.String getBarCode() {
		return getStr("bar_code");
	}

	public void setBorrowTime(java.util.Date borrowTime) {
		set("borrow_time", borrowTime);
	}
	
	public java.util.Date getBorrowTime() {
		return get("borrow_time");
	}

	public void setReturnTime(java.util.Date returnTime) {
		set("return_time", returnTime);
	}
	
	public java.util.Date getReturnTime() {
		return get("return_time");
	}

	public void setBookStatus(java.lang.Integer bookStatus) {
		set("book_status", bookStatus);
	}
	
	public java.lang.Integer getBookStatus() {
		return getInt("book_status");
	}

	public void setReturnStatus(java.lang.Integer returnStatus) {
		set("return_status", returnStatus);
	}
	
	public java.lang.Integer getReturnStatus() {
		return getInt("return_status");
	}

	public void setOverDays(java.lang.Integer overDays) {
		set("over_days", overDays);
	}
	
	public java.lang.Integer getOverDays() {
		return getInt("over_days");
	}

	public void setDeductions(java.lang.Integer deductions) {
		set("deductions", deductions);
	}
	
	public java.lang.Integer getDeductions() {
		return getInt("deductions");
	}

	public void setExplain(java.lang.String explain) {
		set("explain", explain);
	}
	
	public java.lang.String getExplain() {
		return getStr("explain");
	}

	public void setBookImgUrl(java.lang.String bookImgUrl) {
		set("book_img_url", bookImgUrl);
	}
	
	public java.lang.String getBookImgUrl() {
		return getStr("book_img_url");
	}

	public void setUserCode(java.lang.String userCode) {
		set("user_code", userCode);
	}
	
	public java.lang.String getUserCode() {
		return getStr("user_code");
	}

	public void setDptCode(java.lang.String dptCode) {
		set("dpt_code", dptCode);
	}
	
	public java.lang.String getDptCode() {
		return getStr("dpt_code");
	}

	public void setBookId(java.lang.Long bookId) {
		set("book_id", bookId);
	}
	
	public java.lang.Long getBookId() {
		return getLong("book_id");
	}

	public void setCatalogNo(java.lang.String catalogNo) {
		set("catalog_no", catalogNo);
	}
	
	public java.lang.String getCatalogNo() {
		return getStr("catalog_no");
	}

}
