package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBookInventoryItem<M extends BaseBookInventoryItem<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setDel(Boolean del) {
		set("del", del);
	}

	public Boolean getDel() {
		return get("del");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserCode(String createUserCode) {
		set("create_user_code", createUserCode);
	}

	public String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}

	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserCode(String updateUserCode) {
		set("update_user_code", updateUserCode);
	}

	public String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public void setSchoolCode(String schoolCode) {
		set("school_code", schoolCode);
	}

	public String getSchoolCode() {
		return getStr("school_code");
	}

	public void setBookInventoryId(Long bookInventoryId) {
		set("book_inventory_id", bookInventoryId);
	}

	public Long getBookInventoryId() {
		return getLong("book_inventory_id");
	}

	public void setCatalogId(Long catalogId) {
		set("catalog_id", catalogId);
	}

	public Long getCatalogId() {
		return getLong("catalog_id");
	}

	public void setCatalogName(String catalogName) {
		set("catalog_name", catalogName);
	}

	public String getCatalogName() {
		return getStr("catalog_name");
	}

	public void setBookName(String bookName) {
		set("book_name", bookName);
	}

	public String getBookName() {
		return getStr("book_name");
	}

	public void setAuthor(String author) {
		set("author", author);
	}

	public String getAuthor() {
		return getStr("author");
	}

	public void setPublisher(String publisher) {
		set("publisher", publisher);
	}

	public String getPublisher() {
		return getStr("publisher");
	}

	public void setPublishDate(java.util.Date publishDate) {
		set("publish_date", publishDate);
	}

	public java.util.Date getPublishDate() {
		return get("publish_date");
	}

	public void setBarCode(String barCode) {
		set("bar_code", barCode);
	}

	public String getBarCode() {
		return getStr("bar_code");
	}

	public void setCheckNo(String checkNo) {
		set("check_no", checkNo);
	}

	public String getCheckNo() {
		return getStr("check_no");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setPrice(Integer price) {
		set("price", price);
	}

	public Integer getPrice() {
		return getInt("price");
	}

	public void setBookImgUrl(String bookImgUrl) {
		set("book_img_url", bookImgUrl);
	}

	public String getBookImgUrl() {
		return getStr("book_img_url");
	}

	public void setCatalogNo(String catalogNo) {
		set("catalog_no", catalogNo);
	}

	public String getCatalogNo() {
		return getStr("catalog_no");
	}

	public void setBookStatus(Integer bookStatus) {
		set("book_status", bookStatus);
	}

	public Integer getBookStatus() {
		return getInt("book_status");
	}

	public void setInventoryTime(java.util.Date inventoryTime) {
		set("inventory_time", inventoryTime);
	}
	
	public java.util.Date getInventoryTime() {
		return get("inventory_time");
	}

}
