package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBorrowSetting<M extends BaseBorrowSetting<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setDel(Boolean del) {
		set("del", del);
	}

	public Boolean getDel() {
		return get("del");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserCode(String createUserCode) {
		set("create_user_code", createUserCode);
	}

	public String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}

	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserCode(String updateUserCode) {
		set("update_user_code", updateUserCode);
	}

	public String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public void setSchoolCode(String schoolCode) {
		set("school_code", schoolCode);
	}

	public String getSchoolCode() {
		return getStr("school_code");
	}

	public void setMinDeposit(Integer minDeposit) {
		set("min_deposit", minDeposit);
	}

	public Integer getMinDeposit() {
		return getInt("min_deposit");
	}

	public void setMaxDeposit(Integer maxDeposit) {
		set("max_deposit", maxDeposit);
	}

	public Integer getMaxDeposit() {
		return getInt("max_deposit");
	}

	public void setMaxBorrowCount(Integer maxBorrowCount) {
		set("max_borrow_count", maxBorrowCount);
	}

	public Integer getMaxBorrowCount() {
		return getInt("max_borrow_count");
	}

	public void setBorrowDays(Integer borrowDays) {
		set("borrow_days", borrowDays);
	}

	public Integer getBorrowDays() {
		return getInt("borrow_days");
	}

	public void setUnitCost(Integer unitCost) {
		set("unit_cost", unitCost);
	}

	public Integer getUnitCost() {
		return getInt("unit_cost");
	}

	public void setFirstBeyondDays(Integer firstBeyondDays) {
		set("first_beyond_days", firstBeyondDays);
	}

	public Integer getFirstBeyondDays() {
		return getInt("first_beyond_days");
	}

	public void setFirstBeyondUnitCost(Integer firstBeyondUnitCost) {
		set("first_beyond_unit_cost", firstBeyondUnitCost);
	}

	public Integer getFirstBeyondUnitCost() {
		return getInt("first_beyond_unit_cost");
	}

	public void setSecondBeyondDays(Integer secondBeyondDays) {
		set("second_beyond_days", secondBeyondDays);
	}

	public Integer getSecondBeyondDays() {
		return getInt("second_beyond_days");
	}

	public void setSecondBeyondUnitCost(Integer secondBeyondUnitCost) {
		set("second_beyond_unit_cost", secondBeyondUnitCost);
	}

	public Integer getSecondBeyondUnitCost() {
		return getInt("second_beyond_unit_cost");
	}

	public void setMaxBorrowCost(Integer maxBorrowCost) {
		set("max_borrow_cost", maxBorrowCost);
	}

	public Integer getMaxBorrowCost() {
		return getInt("max_borrow_cost");
	}

	public void setBeyondWarningDays(Integer beyondWarningDays) {
		set("beyond_warning_days", beyondWarningDays);
	}

	public Integer getBeyondWarningDays() {
		return getInt("beyond_warning_days");
	}

	public void setUnreturnWarningDays(Integer unreturnWarningDays) {
		set("unreturn_warning_days", unreturnWarningDays);
	}

	public Integer getUnreturnWarningDays() {
		return getInt("unreturn_warning_days");
	}

	public void setDepositWarning(Integer depositWarning) {
		set("deposit_warning", depositWarning);
	}

	public Integer getDepositWarning() {
		return getInt("deposit_warning");
	}

	public void setUncheckWarningDays(Integer uncheckWarningDays) {
		set("uncheck_warning_days", uncheckWarningDays);
	}

	public Integer getUncheckWarningDays() {
		return getInt("uncheck_warning_days");
	}

	public void setDepositAuditFlag(Short depositAuditFlag) {
		set("deposit_audit_flag", depositAuditFlag);
	}

	public Short getDepositAuditFlag() {
		return getShort("deposit_audit_flag");
	}

	public void setSource(String source) {
		set("source", source);
	}

	public String getSource() {
		return getStr("source");
	}

}
