package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSetting<M extends BaseSetting<M>> extends Model<M> implements IBean {

	public void setAccess(java.lang.String access) {
		set("access", access);
	}
	
	public java.lang.String getAccess() {
		return getStr("access");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setColumns(java.lang.String columns) {
		set("columns", columns);
	}
	
	public java.lang.String getColumns() {
		return getStr("columns");
	}

	public void setPageSize(java.lang.Short pageSize) {
		set("page_size", pageSize);
	}
	
	public java.lang.Short getPageSize() {
		return getShort("page_size");
	}

	public void setScrollX(java.lang.Short scrollX) {
		set("scroll_x", scrollX);
	}
	
	public java.lang.Short getScrollX() {
		return getShort("scroll_x");
	}

}
