package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBookDamaged<M extends BaseBookDamaged<M>> extends Model<M> implements IBean {

	public void setRecorder(String recorder) {
		set("recorder", recorder);
	}

	public String getRecorder() {
		return getStr("recorder");
	}

	public void setBorrowerName(String borrowerName) {
		set("borrower_name", borrowerName);
	}

	public String getBorrowerName() {
		return getStr("borrower_name");
	}

	public void setRepairer(String repairer) {
		set("repairer", repairer);
	}

	public String getRepairer() {
		return getStr("repairer");
	}

	public void setBookStatus(Integer bookStatus) {
		set("book_status", bookStatus);
	}

	public Integer getBookStatus() {
		return getInt("book_status");
	}

	public void setBorrowId(Long borrowId) {
		set("borrow_id", borrowId);
	}

	public Long getBorrowId() {
		return getLong("borrow_id");
	}

	public void setBarCode(String barCode) {
		set("bar_code", barCode);
	}

	public String getBarCode() {
		return getStr("bar_code");
	}

	public void setExplain(String explain) {
		set("explain", explain);
	}

	public String getExplain() {
		return getStr("explain");
	}

	public void setBookName(String bookName) {
		set("book_name", bookName);
	}

	public String getBookName() {
		return getStr("book_name");
	}

	public void setAuthor(String author) {
		set("author", author);
	}

	public String getAuthor() {
		return getStr("author");
	}

	public void setRecordTime(java.util.Date recordTime) {
		set("record_time", recordTime);
	}

	public java.util.Date getRecordTime() {
		return get("record_time");
	}

	public void setRepairTime(java.util.Date repairTime) {
		set("repair_time", repairTime);
	}

	public java.util.Date getRepairTime() {
		return get("repair_time");
	}

	public void setDeductions(Integer deductions) {
		set("deductions", deductions);
	}

	public Integer getDeductions() {
		return getInt("deductions");
	}

	public void setUnitCode(String unitCode) {
		set("unit_code", unitCode);
	}

	public String getUnitCode() {
		return getStr("unit_code");
	}

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setLastStatus(Integer lastStatus) {
		set("last_status", lastStatus);
	}

	public Integer getLastStatus() {
		return getInt("last_status");
	}

	public void setDel(Boolean del) {
		set("del", del);
	}

	public Boolean getDel() {
		return get("del");
	}

	public void setJudge(Integer judge) {
		set("judge", judge);
	}

	public Integer getJudge() {
		return getInt("judge");
	}

	public void setJudger(String judger) {
		set("judger", judger);
	}

	public String getJudger() {
		return getStr("judger");
	}

	public void setRecorderCode(String recorderCode) {
		set("recorder_code", recorderCode);
	}

	public String getRecorderCode() {
		return getStr("recorder_code");
	}

	public void setRepairerCode(String repairerCode) {
		set("repairer_code", repairerCode);
	}

	public String getRepairerCode() {
		return getStr("repairer_code");
	}

	public void setJudgerCode(String judgerCode) {
		set("judger_code", judgerCode);
	}

	public String getJudgerCode() {
		return getStr("judger_code");
	}

	public void setJudgeTime(java.util.Date judgeTime) {
		set("judge_time", judgeTime);
	}
	
	public java.util.Date getJudgeTime() {
		return get("judge_time");
	}

}
