package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBookBarCode<M extends BaseBookBarCode<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setDel(Boolean del) {
		set("del", del);
	}

	public Boolean getDel() {
		return get("del");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserCode(String createUserCode) {
		set("create_user_code", createUserCode);
	}

	public String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}

	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserCode(String updateUserCode) {
		set("update_user_code", updateUserCode);
	}

	public String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public void setSchoolCode(String schoolCode) {
		set("school_code", schoolCode);
	}

	public String getSchoolCode() {
		return getStr("school_code");
	}

	public void setBookStorageId(Long bookStorageId) {
		set("book_storage_id", bookStorageId);
	}

	public Long getBookStorageId() {
		return getLong("book_storage_id");
	}

	public void setBookStorageItemId(Long bookStorageItemId) {
		set("book_storage_item_id", bookStorageItemId);
	}

	public Long getBookStorageItemId() {
		return getLong("book_storage_item_id");
	}

	public void setBookId(Long bookId) {
		set("book_id", bookId);
	}

	public Long getBookId() {
		return getLong("book_id");
	}

	public void setBarCode(String barCode) {
		set("bar_code", barCode);
	}

	public String getBarCode() {
		return getStr("bar_code");
	}

	public void setCheckNo(String checkNo) {
		set("check_no", checkNo);
	}

	public String getCheckNo() {
		return getStr("check_no");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public void setPrice(Integer price) {
		set("price", price);
	}

	public Integer getPrice() {
		return getInt("price");
	}

}
