package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAsset<M extends BaseAsset<M>> extends Model<M> implements IBean {

	public void setId(String id) {
		set("id", id);
	}

	public String getId() {
		return getStr("id");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setUrl(String url) {
		set("url", url);
	}

	public String getUrl() {
		return getStr("url");
	}

	public void setExt(String ext) {
		set("ext", ext);
	}

	public String getExt() {
		return getStr("ext");
	}

	public void setSize(Long size) {
		set("size", size);
	}

	public Long getSize() {
		return getLong("size");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return getStr("type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setSaveTime(java.util.Date saveTime) {
		set("save_time", saveTime);
	}

	public java.util.Date getSaveTime() {
		return get("save_time");
	}

	public void setSaved(Boolean saved) {
		set("saved", saved);
	}

	public Boolean getSaved() {
		return get("saved");
	}

}
