package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBookInventory<M extends BaseBookInventory<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setDel(Boolean del) {
		set("del", del);
	}

	public Boolean getDel() {
		return get("del");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserCode(String createUserCode) {
		set("create_user_code", createUserCode);
	}

	public String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}

	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserCode(String updateUserCode) {
		set("update_user_code", updateUserCode);
	}

	public String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public void setSchoolCode(String schoolCode) {
		set("school_code", schoolCode);
	}

	public String getSchoolCode() {
		return getStr("school_code");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return getStr("name");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return getInt("status");
	}

}
