package com.jfnice.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBorrowBook<M extends BaseBorrowBook<M>> extends Model<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return getLong("id");
	}

	public void setDel(Boolean del) {
		set("del", del);
	}

	public Boolean getDel() {
		return get("del");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setCreateUserCode(String createUserCode) {
		set("create_user_code", createUserCode);
	}

	public String getCreateUserCode() {
		return getStr("create_user_code");
	}

	public void setCreateUserName(String createUserName) {
		set("create_user_name", createUserName);
	}

	public String getCreateUserName() {
		return getStr("create_user_name");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setUpdateUserCode(String updateUserCode) {
		set("update_user_code", updateUserCode);
	}

	public String getUpdateUserCode() {
		return getStr("update_user_code");
	}

	public void setSchoolCode(String schoolCode) {
		set("school_code", schoolCode);
	}

	public String getSchoolCode() {
		return getStr("school_code");
	}

	public void setGrdCode(String grdCode) {
		set("grd_code", grdCode);
	}

	public String getGrdCode() {
		return getStr("grd_code");
	}

	public void setGrdName(String grdName) {
		set("grd_name", grdName);
	}

	public String getGrdName() {
		return getStr("grd_name");
	}

	public void setClsCode(String clsCode) {
		set("cls_code", clsCode);
	}

	public String getClsCode() {
		return getStr("cls_code");
	}

	public void setClsName(String clsName) {
		set("cls_name", clsName);
	}

	public String getClsName() {
		return getStr("cls_name");
	}

	public void setStuCode(String stuCode) {
		set("stu_code", stuCode);
	}

	public String getStuCode() {
		return getStr("stu_code");
	}

	public void setSno(String sno) {
		set("sno", sno);
	}

	public String getSno() {
		return getStr("sno");
	}

	public void setDptName(String dptName) {
		set("dpt_name", dptName);
	}

	public String getDptName() {
		return getStr("dpt_name");
	}

	public void setBorrower(String borrower) {
		set("borrower", borrower);
	}

	public String getBorrower() {
		return getStr("borrower");
	}

	public void setCatalogName(String catalogName) {
		set("catalog_name", catalogName);
	}

	public String getCatalogName() {
		return getStr("catalog_name");
	}

	public void setCheckNo(String checkNo) {
		set("check_no", checkNo);
	}

	public String getCheckNo() {
		return getStr("check_no");
	}

	public void setPrice(Integer price) {
		set("price", price);
	}

	public Integer getPrice() {
		return getInt("price");
	}

	public void setBookName(String bookName) {
		set("book_name", bookName);
	}

	public String getBookName() {
		return getStr("book_name");
	}

	public void setAuthor(String author) {
		set("author", author);
	}

	public String getAuthor() {
		return getStr("author");
	}

	public void setPublisher(String publisher) {
		set("publisher", publisher);
	}

	public String getPublisher() {
		return getStr("publisher");
	}

	public void setPublishDate(java.util.Date publishDate) {
		set("publish_date", publishDate);
	}

	public java.util.Date getPublishDate() {
		return get("publish_date");
	}

	public void setBarCode(String barCode) {
		set("bar_code", barCode);
	}

	public String getBarCode() {
		return getStr("bar_code");
	}

	public void setBorrowTime(java.util.Date borrowTime) {
		set("borrow_time", borrowTime);
	}

	public java.util.Date getBorrowTime() {
		return get("borrow_time");
	}

	public void setReturnTime(java.util.Date returnTime) {
		set("return_time", returnTime);
	}

	public java.util.Date getReturnTime() {
		return get("return_time");
	}

	public void setBookStatus(Integer bookStatus) {
		set("book_status", bookStatus);
	}

	public Integer getBookStatus() {
		return getInt("book_status");
	}

	public void setReturnStatus(Integer returnStatus) {
		set("return_status", returnStatus);
	}

	public Integer getReturnStatus() {
		return getInt("return_status");
	}

	public void setOverDays(Integer overDays) {
		set("over_days", overDays);
	}

	public Integer getOverDays() {
		return getInt("over_days");
	}

	public void setDeductions(Integer deductions) {
		set("deductions", deductions);
	}

	public Integer getDeductions() {
		return getInt("deductions");
	}

	public void setExplain(String explain) {
		set("explain", explain);
	}

	public String getExplain() {
		return getStr("explain");
	}

	public void setBookImgUrl(String bookImgUrl) {
		set("book_img_url", bookImgUrl);
	}

	public String getBookImgUrl() {
		return getStr("book_img_url");
	}

	public void setUserCode(String userCode) {
		set("user_code", userCode);
	}

	public String getUserCode() {
		return getStr("user_code");
	}

	public void setDptCode(String dptCode) {
		set("dpt_code", dptCode);
	}

	public String getDptCode() {
		return getStr("dpt_code");
	}

	public void setBookId(Long bookId) {
		set("book_id", bookId);
	}

	public Long getBookId() {
		return getLong("book_id");
	}

	public void setCatalogNo(String catalogNo) {
		set("catalog_no", catalogNo);
	}

	public String getCatalogNo() {
		return getStr("catalog_no");
	}

}
